export enum GroupCode {
    CODE_LIST_ADMINISTRATOR = 'CODE_LIST_ADMINISTRATOR',
    IIHF_MANAGER = 'IIHF_MANAGER',
    IIHF_SUPERVISOR = 'IIHF_SUPERVISOR',
    ORGANIZER = 'ORGANIZER',
    USER_ADMINISTRATOR = 'USER_ADMINISTRATOR',
}
